# Generated by Django 5.2 on 2026-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_academyeventsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_chat',
            field=models.BooleanField(default=True, help_text='Enable the Daily chat in the embedded call frame for this event.'),
        ),
    ]
